### ISSUE TITLE
Lamp colour display does not work as intended

### ISSUE THREAD

**Issue by avataryt** [sb12/OSMStreetLight#3]
Issue #2 seems to be the same, but I think I can't re-open it. I was running into the same/a similar problem. 

During the last weeks, I started to map street lights in Cologne (http://inai.de/sl/#15/50.9122/6.9717). Setting light:colour seems to be ignored - all street lights are displayed in yellow. While I'm not a coder this seems to me caused by how the SVG file names are created/parsed in parse_scripts.js.

* I typically did not set light:method during my initial mapping. In this case it seems that always the default colour yellow is used.
* Due to the order of the if-statements in parse_scripts.js, light:method seems to overwrite the colour value in case one is set via light:colour. IMHO if light:colour is set, this always should be the setting with priority. People might mix up light methods, but it's unlike that they'll mix up the colour.

Initially, I thought I can fix this just by adding light:mode=electric to all the street lights I mapped as images like electric_white.svg do exist. But **it seems that everything besides light:method is having no effect on the color display**.

You can find a demo of this behavior here: http://inai.de/sl/#19/50.91153/6.97258

**Comment by sb12** [comment]
Thanks for your report. 
Please note that  http://inai.de/sl/ is run by @jengelh and uses a slighty different codebase.
Nonetheless there are a few valid points in this issue:
- As there are special not-colour-based renderings for led, mercury, fluorescent and gas lamps, the colour was ignored for these lamp types. I now changed it, so that if you use an unusual colour (e.g. an orange led lamp) for these lamp types it will change to colour rendering.
- I also added support for yellow colour and fixed the led rendering. 

You will find the new rendering at http://osmstreetlight.bplaced.net/#15/50.9122/6.9717 
Have fun with mapping street lamps and please let me know, if you find any other issues.

**Comment by avataryt** [comment]
Thanks for the quick fix and all your work. Works like a charm.
Great to see Köln-Bayenthal in "a new light" ;-)
