### ISSUE TITLE
Yellow spinner background too poor contrast

### ISSUE THREAD

**Issue by jidanni** [sb12/OSMStreetLight#6]
The spinner background is yellow upon loading data, then turns white.

However one cannot tell if it turned white, or our eyes just adjusted the colors in our brain.

Therefore please use red instead of yellow.

**Comment by jidanni** [comment]
In fact one would think:
- When the yellow turns white, that means I'm already looking at all the lamps in that area.

But in fact one should wait for about 20 more seconds before giving up thinking there are no lamps in that area...

And
- When the spinner stops, that means I'm already looking at all the lamps in that area.

But in fact due to #7, the spinner may never stop.

**Comment by sb12** [comment]
The spinner background highlights yellow for 0.7s, every time new data is requested from overpass API (usually when map is moved or zoomed). It will fade in and out in these 0.7s, that's why it seems that the brain might adjust the color. 
As there is no real meaning in the yellow/white color, I do not see a reason why I should change it.

**Comment by jidanni** [comment]
Perhaps add a mouseover to the spinner, explaining all the things it does/means.
