### ISSUE TITLE
Spinner never stops spinning

### ISSUE THREAD

**Issue by jidanni** [sb12/OSMStreetLight#7]
The spinner never stops spinning, ever. Sometimes.

**Comment by jidanni** [comment]
OK, we see in Developer Tools it was due to HTTP 429 and 503's perhaps.

Anyway maybe it should give up, as the problem seems to happen often.

**Comment by sb12** [comment]
Thanks for your report.
I just tried to reproduce your problem. But for me this never seems to happen. It might be though that it happens based on browser, internet provider or network quality.
Can you give some details about the HTTP errors you are seeing and maybe also the browser you are using? I can then see if I can give some error feedback instead of the never-stopping spinning.

**Comment by sb12** [comment]
Just tried in Chrome and there I also randomly get these http errors for the overpass requests. I will see if I can improve the error handling.

**Comment by sb12** [comment]
I now added a timeout of 30s for overpass requests. In case of a timeout or an HTTP error, the spinner will now turn red and disappear slowly. 
Please let me know in case you still have problems with the spinner or there are any problems with the timeout.
